#!/usr/bin/env python

import sys
import commands

prefix_branch_name=True

message_file = sys.argv[1]

current_branch = commands.getoutput("git branch | grep '*'").replace("* ", "")

prefix_commit_msg=""
if prefix_branch_name:
	prefix_commit_msg = current_branch.split("_")[0]
else:
	prefix_commit_msg = current_branch

with open(message_file, 'r') as read_file:
	original_message = read_file.read()

newmessage = original_message.replace("[branch_name]", prefix_commit_msg)

with open(message_file, 'w') as write_file:
	write_file.write(newmessage)

#for_debug

