" Size settings
set fuoptions=maxvert,maxhorz

" window size
"au GUIEnter * set fullscreen
set lines=100
set columns=120
" 
set background=dark
set imdisable	
set showtabline=2
"set transparency=10	
set antialias
set guifont=Monaco:h14
"set guifont=Ricty\ Discord:h13
colorscheme macvim
