"##### Encoding
set encoding=utf-8
scriptencoding utf-8

"##### NeoBundle
if has('vim_starting')
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

" Initialize NeoBundle
call neobundle#begin(expand('~/.vim/bundle/'))

"##### NeoBundleInstall
" download :NeoBundleInstall
" update :NeoBundleUpdate vimfiler
NeoBundle 'itchyny/lightline.vim'
NeoBundle 'joonty/vdebug'
NeoBundle 'nathanaelkane/vim-indent-guides'
NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/vimfiler'
NeoBundle 'tpope/vim-fugitive'

call neobundle#end()
" Required:
filetype plugin indent on
" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck

set laststatus=2 "setting for lightline.vim

" read plugin
if filereadable(expand('$HOME/dotfiles/vim/plugin/lightline'))
  source $HOME/dotfiles/vim/plugin/lightline
endif

if filereadable(expand('$HOME/dotfiles/vim/plugin/vim-indent-guides'))
  source $HOME/dotfiles/vim/plugin/vim-indent-guides
endif

"##### Display settings
"set clipboard=unnamed,autoselect
set list
set listchars=tab:»-,trail:-,eol:\↲\,extends:»,precedes:«,nbsp:%
set number
set showmatch
set tabstop=4
set title
syntax on

"##### Indent
"set autoindent 
"set shiftwidth=4 "indent 4 spaces
"set smartindent

set statusline=%F%m%r%h%w\%=[TYPE=%Y]\[FORMAT=%{&ff}]\[ENC=%{&fileencoding}]\[LOW=%l/%L]

"#####Search#####
set hlsearch
set ignorecase
set nowrapscan
set smartcase

hi ZenkakuSpace cterm=underline ctermfg=lightblue ctermbg=gray
match ZenkakuSpace /　/

" restore last cursor position
if has("autocmd")
  autocmd BufReadPost *
    \ if line("'\"") > 0 && line ("'\"") <= line("$") |
    \   exe "normal! g'\"" |
    \ endif
endif

