"##### Encoding
set encoding=utf-8
scriptencoding utf-8

"##### NeoBundle
"if has('vim_starting')
"  set runtimepath+=~/.vim/bundle/neobundle.vim/
"endif

" Initialize NeoBundle
"call neobundle#begin(expand('~/.vim/bundle/'))

"##### NeoBundleInstall
" download :NeoBundleInstall
" update :NeoBundleUpdate vimfiler
"NeoBundle 'derekwyatt/vim-scala'
"NeoBundle 'itchyny/lightline.vim'
"NeoBundle 'joonty/vdebug'
"NeoBundle 'nathanaelkane/vim-indent-guides'
"NeoBundle 'Shougo/unite.vim'
"NeoBundle 'Shougo/vimfiler'
"NeoBundle 'tpope/vim-fugitive'

"call neobundle#end()

if &compatible
  set nocompatible
endif
set runtimepath+=${HOME}/.vim/dein/repos/github.com/Shougo/dein.vim

call dein#begin(expand('~/.cache/dein'))

call dein#add('derekwyatt/vim-scala')
call dein#add('itchyny/lightline.vim')
call dein#add('jelera/vim-javascript-syntax')
call dein#add('joonty/vdebug')
call dein#add('nathanaelkane/vim-indent-guides')
call dein#add('othree/html5.vim')
call dein#add('scrooloose/nerdtree')
call dein#add('Shougo/neocomplete.vim')
call dein#add('Shougo/unite.vim')
call dein#add('Shougo/vimfiler')
call dein#add('tpope/vim-fugitive')
call dein#add('tpope/vim-markdown')
call dein#add('Xuyuanp/nerdtree-git-plugin')

if dein#check_install()
  call dein#install()
endif

"NeoBundleCheck

set laststatus=2 "setting for lightline.vim

" read plugin
if filereadable(expand('$HOME/dotfiles/vim/plugin/lightline'))
  source $HOME/dotfiles/vim/plugin/lightline
endif

if filereadable(expand('$HOME/dotfiles/vim/plugin/vim-indent-guides'))
  source $HOME/dotfiles/vim/plugin/vim-indent-guides
endif

"##### Display settings
"set clipboard=unnamed,autoselect
set list
set listchars=tab:»-,trail:-,eol:\↲\,extends:»,precedes:«,nbsp:%
set number
set showmatch
set tabstop=4
set title
syntax on

"##### Indent
"set autoindent 
"set shiftwidth=4 "indent 4 spaces
"set smartindent

set statusline=%F%m%r%h%w\%=[TYPE=%Y]\[FORMAT=%{&ff}]\[ENC=%{&fileencoding}]\[LOW=%l/%L]

"#####Search#####
set hlsearch
set ignorecase
set nowrapscan
set smartcase

hi ZenkakuSpace cterm=underline ctermfg=lightblue ctermbg=gray
match ZenkakuSpace /　/

" restore last cursor position
if has("autocmd")
  autocmd BufReadPost *
    \ if line("'\"") > 0 && line ("'\"") <= line("$") |
    \   exe "normal! g'\"" |
    \ endif
endif

