# zshrc
fpath=(/usr/local/share/zsh-completions $fpath)
autoload -Uz compinit
compinit -u # Ignore insecure files message

alias ll='ls -l'
alias vim='nvim'

#
autoload -U compinit
compinit

# history command settings
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt extended_history
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt share_history

zshaddhistory() {
  local line=${1%%$'\n'}
  local cmd=${line%% *}

  [[ ${cmd} != (l|l[sal])
  && ${cmd} != (exit|history|m|man|pwd|who)
  ]]
}

# read plugin
cd && for plugin_file in ~/dotfiles/zsh/plugin/*; do
  source $plugin_file
done

# read zshrc.specific
source ${HOME}/dotfiles/zsh/zshrc.specific

