# zshrc
fpath=(/usr/local/share/zsh-completions $fpath)
autoload -Uz compinit
compinit -u # Ignore insecure files message

# history command settings
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt extended_history
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt share_history

zshaddhistory() {
  local line=${1%%$'\n'}
  local cmd=${line%% *}

  [[ ${cmd} != (l|l[sal])
  && ${cmd} != (exit|history|m|man|pwd|who)
  ]]
}

# alias
source ${HOME}/dotfiles/zsh/alias

# read plugin
cd && for plugin_file in ~/dotfiles/zsh/plugin/*; do
  source $plugin_file
done

# gitignore file
# read zshrc.specific
ZSHRC_SPECIFIC=${HOME}/dotfiles/zsh/zshrc.specific
if [[ -e ${ZSHRC_SPECIFIC} ]]; then
  source ${ZSHRC_SPECIFIC}
fi

autoload -Uz add-zsh-hook
add-zsh-hook chpwd chpwd_func
function chpwd_func() {
  sed -i -e "s:^cd .* #catcat:cd $PWD #catcat:g" ~/.zshrc
}
cd ${HOME} #catcat

